"""create models

Revision ID: 81cfc2f0e907
Revises: 
Create Date: 2018-12-20 11:41:21.787436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cfc2f0e907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goodsinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('seller', sa.String(length=256), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('reviews', sa.String(length=64), nullable=True),
    sa.Column('rankings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goodsinfo')
    # ### end Alembic commands ###
